version: "3"
networks:
  expense:
volumes:
  mysql:
services:
  mysql:
    image: silpa11/mysql:v1
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql
  backend:
    image: silpa11/backend:v1
    container_name: backend
    depends_on:
      - mysql
  frontend:
    image: silpa11/frontend:v1
    container_name: frontend
    depends_on:
      - backend
    ports:
      - 80:80




  
